### ISSUE TITLE
Getting error in presence example

### ISSUE THREAD

**Issue by chaimleu** [wiomoc/whatsappweb-rs#2]
Hey,
I tried to run the presence example. I succeeded to login but then it crashed and throwed an error:
`2018-07-03 19:13:01 INFO  [ws] Queuing connection to wss://w7.web.whatsapp.com/ws
2018-07-03 19:13:04 INFO  [presence] new state: Connected
thread '<unnamed>' panicked at 'called 'Result::unwrap()' on an 'Err' value: Error(Msg("Node has invalid binary format"), State { next_error: Some(Error(Msg("Couldn\'t read node content (list), node decription: response"), State { next_error: Some(Error(Msg("Couldn\'t read list item: 1, size: 2"), State { next_error: Some(Error(Msg("Couldn\'t read attribute :jid, node decription: user"), State { next_error: Some(Error(Msg("invalid jid surfix broadcast"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:916:5
note: Run with 'RUST_BACKTRACE=1' for a backtrace.
thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Any', libcore/result.rs:916:5
`

Any idea how to fix it?
I only replaced the number in the example, and didn't changed anything else.

Thank you very much!

**Comment by wiomoc** [comment]
Duplicate to #1 
Auhh, I think I have overlooked broadcast jid.
Im on this.
Thank you

**Comment by wiomoc** [comment]
hotfix is on master

**Comment by azharuddinkhan8898** [comment]
@wiomoc 
Getting same error.
